2021-04_UW_M027:
  Index_F01-Index_R01:
    index_type: Index_primer
    fwd_index: Index_F01
    rev_index: Index_R01
  Index_F02-Index_R02:
    index_type: Index_primer
    fwd_index: Index_F02
    rev_index: Index_R02
  Index_F03-Index_R03:
    index_type: Index_primer
    fwd_index: Index_F03
    rev_index: Index_R03
  Index_F04-Index_R04:
    index_type: Index_primer
    fwd_index: Index_F04
    rev_index: Index_R04
  Index_F05-Index_R01:
    index_type: Index_primer
    fwd_index: Index_F05
    rev_index: Index_R01
  Index_F06-Index_R02:
    index_type: Index_primer
    fwd_index: Index_F06
    rev_index: Index_R02
  Index_F07-Index_R03:
    index_type: Index_primer
    fwd_index: Index_F07
    rev_index: Index_R03
  Index_F08-Index_R04:
    index_type: Index_primer
    fwd_index: Index_F08
    rev_index: Index_R04
  Index_F09-Index_R01:
    index_type: Index_primer
    fwd_index: Index_F09
    rev_index: Index_R01
  Index_F10-Index_R02:
    index_type: Index_primer
    fwd_index: Index_F10
    rev_index: Index_R02
    rev_adapter: GTCTCGTGGGCTCGG